baseurl: ""

title      : evo The Midlands - Bond Origination & Home Loan Experts in xxxSuburb, xxxCity, xxxProvince
email      : sueann.weber@evogroup.co.za
description: Contact evo Midlands from SUBURB-NAME, CITY-NAME to help you with home loan. I have 23 years banking experience of which 10 years are home loans experience. I also have 8 years of bond origination experience. 
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: G-GXL51EECEE

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/logo.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]

group: evo Home Loans

company: evo YOUR BRANCH NAME

url: www.evomidlands.co.za

address: NO. ROAD-NAME, SUBURB-NAME, TOWN-NAME, PROVINCE, POSTAL-CODE
