baseurl: ""

title      : evo The Midlands - Bond Origination & Home Loan Experts in xxxSuburb, xxxCity, xxxProvince
email      : sueann.weber@evogroup.co.za
description: Contact evo YOUR BRANCH NAME from SUBURB-NAME, CITY-NAME to help you with home loan. We are seasoned property professionals that specialize in mortgages and property finance with 28 years of experience. Our experience ranges from sales to finance and she specializes in bonds, home loans and origination. We are committed to excellent client service, building long-term relationships.
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: G-GXL51EECEE

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/logo.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]

group: evo Group

company: evo YOUR BRANCH NAME

url: www.evomidlands.co.za

address: NO. ROAD-NAME, SUBURB-NAME, TOWN-NAME, PROVINCE, POSTAL-CODE
