baseurl: ""

title: evo Midlands - Bond Origination, Home Loans Experts in Howick, & KZN Midlands.
email:
description: evo Midlands - Expert bond origination to secure your ideal home loan. We find competitive rates and personalized financing solutions to make your property dreams reality.
author: Pieter Oosthuizen

analytics:
  google: G-XXX

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/evo-midlands-logo.png

exclude: [node_modules, webpack-config.js, package.json, package-lock.json]

group: evo Homeloans

company: evo Midlands

url: https://evohomeloans.co.za

address: KwaZulu-Natal, 40 Main Road, Howick, 3290
