baseurl: ""

title: Bond Squad - Bond Origination & Home Loans Experts in CT & KZN.
email:
description: Achieve your property dreams with Bond Squad. Founded by Hayley Craig and Lara Patterson, we secure the best home loan deals through expert bond origination.
author: Eben Roux / Pieter Oosthuizen

analytics:
  google: G-XXX

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/evo-midlands-logo.png

exclude: [node_modules, webpack-config.js, package.json, package-lock.json]

group: evo Homeloans

company: evo Midlands

url: https://evohomeloans.co.za

address: KwaZulu-Natal, 40 Main Road, Howick, 3290
