baseurl: ""

title      : evo The Midlands - Bond Origination & Home Loan Experts in Howick | KZN Midlands
email      : 
description: Contact evo Midlands from Howick, in the KwaZulu-Natal Midlands to help you with home loan. With banking and homeloan experience I am here to help you with your bond origination. 
author     : Eben Roux / Pieter Oosthuizen

analytics:
  google: G-GXL51EECEE

collections:
  portfolio:

markdown: kramdown

webserver_headers:
  - - Access-Control-Allow-Origin
    - "*"
  - - Access-Control-Allow-Methods
    - GET, OPTIONS, HEAD

logo:
  path: /assets/logo.png

exclude: [node_modules,webpack-config.js,package.json,package-lock.json]

group: evo Home Loans

company: evo Midlands

url: www.evomidlands.co.za

address: ​Unit 4, 44 Main Street, Howick, Kwa-Zulu Natal